### DISCUSSION TITLE
setting cronj jobs from another host on same docker network

### DISCUSSION THREAD

**Discussion by acappelletti** [alseambusher/crontab-ui#234] [General]
Hi all,
it's not clear to me if it's possible read and config cronjobs from another host.
I got a docker compose file with 4 app, which one of this is crontab-ui.

Ok, it perfectly works in own host, but I would like to connect and edit another cron for the host XXXX.
Naturally all 4 app are on same network...

Can you explain to me if it's possible or do I need to install crontab-ui inside the dockerized app?

Thanks. Alen
```
  crontab-ui:
    image: ${crontabui}
    container_name: crontab-ui 
    hostname: crontab-ui
    restart: always
    environment:
      CRON_DB_PATH: /crontab-ui/bkp
    volumes:
      - /etc/docker/crontab-ui:/crontab-ui/bkp
    ports:
      - "8005:8000"
```
