### ISSUE TITLE
dockerized crontab-ui jobs will not run without trick

### ISSUE THREAD

**Issue by tayyebi** [alseambusher/crontab-ui#208]
Before all thank you for your amazing project!

I'm using this cool tool on docker. My `docker-compose.yml` is shown below:
```
version: '3.7'

services:
  crontab-ui:
    container_name: crontab-ui
    build: .
    image: alseambusher/crontab-ui
    network_mode: bridge
    ports:
      - 3030:8000
    env_file: variables.env
    volumes:
      # - /var/spool/cron/crontabs/my_username_here:/etc/crontabs/root
      - /etc/cron.d:/etc/crontabs
      - ./data/crontabs:/crontab-ui/crontabs
```

As you already know **If we are decided to add a cronjob to cron.d, we have to mention the username, after time configuration.
So, this will work for `crontab -e`:
```
* * * * * wall Hello from crontabs $(date)
```
But it will definitely not work in `cron.d` and it should be:
```
* * * * * wall my_username_here Hello from cron.d $(date)
```

As you can see in the image below, I used the last _time_ text box to define my username! Can we add an input for that?
(I'll be honored to volunteer this task, if you let me know your idea about it.)

![image](https://user-images.githubusercontent.com/14053493/190185847-8b159365-9200-474d-9d1f-257868d4154b.png)

Cheers

**Comment by tayyebi** [comment]
Crontab-UI home page (Please kindly pay attention to time column):

![image](https://user-images.githubusercontent.com/14053493/190188122-1f400817-e71d-454e-9b4a-5daaf402f740.png)

Result on my host machine:

![image](https://user-images.githubusercontent.com/14053493/190187959-cc1639ec-9918-470a-9116-85746ca64661.png)

**Comment by icemtel** [comment]
Hey @tayyebi  I don't completely understand your problem, but why wouldn't you add your username as a part of the "Command" field?

**Comment by icemtel** [comment]
Unrelated to your issue, but you probably understand this better than I do: 

- Does crontab-ui installed with docker work properly (meaning that it can read and write to the real crontab file and see execution log) only if the crontabs folder is mounted?
- Does it update the crontab file only if "save to crontab" is pressed?

**Comment by tayyebi** [comment]
Dear @icemtel it's working like a charm!

> but why wouldn't you add your username as a part of the "Command" field?

Because if add add the username in `command` field, the saved file will contain `((({ username_here` which will not work!

**Comment by tayyebi** [comment]
Let me share my `docker-compose.yml`:
```
version: '3.7'

services:
  crontab-ui:
    container_name: crontab-ui
    build: .
    image: alseambusher/crontab-ui
    network_mode: bridge
    ports:
      - 8080:8000
    env_file: variables.env
    volumes:
      # - /var/spool/cron/crontabs/ubuntu:/etc/crontabs/root
      - /etc/cron.d:/etc/crontabs
      - ~/d:/d
      - ./data/crontabs:/crontab-ui/crontabs
      - /tmp/crontab-ui:/tmp
    working_dir: /d
```
and the dir:
```
crontab-ui$ ls
Dockerfile  app.js      crontabs            public            variables.env
LICENSE.md  app.json    data                restore.js        views
Makefile    bin         docker-compose.yml  routes.js
README      config      package-lock.json   supervisord.conf
README.md   crontab.js  package.json        tests
```
