### ISSUE TITLE
install on my current setup PHP:8.1-FPM

### ISSUE THREAD

**Issue by arcanisgk** [alseambusher/crontab-ui#213]
i have this setup:

Dockerfile:

```bash
FROM php:8.1.11-fpm

WORKDIR "/application"

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get update && apt-get -y install --no-install-recommends --fix-missing cron

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN install-php-extensions pdo_mysql
RUN install-php-extensions Reflection
RUN install-php-extensions session
RUN install-php-extensions SimpleXML
RUN install-php-extensions SPL
RUN install-php-extensions sqlite3
RUN IPE_GD_WITHOUTAVIF=1 install-php-extensions gd
RUN install-php-extensions curl
RUN install-php-extensions imap
RUN IPE_ICU_EN_ONLY=1 install-php-extensions intl
RUN IPE_ICU_EN_ONLY=1 install-php-extensions http
RUN install-php-extensions json
RUN install-php-extensions mailparse
RUN install-php-extensions mbstring
RUN install-php-extensions readline
RUN install-php-extensions soap
RUN install-php-extensions xml
RUN install-php-extensions xmlrpc
RUN install-php-extensions bz2
RUN install-php-extensions zlib
RUN install-php-extensions dba
RUN install-php-extensions ldap
RUN install-php-extensions xdebug
RUN install-php-extensions @composer
```

docker composer yaml:

```yaml
version: "3.9"
services:
  mysql:
    container_name: mysql
    image: 'mysql:8.0'
    working_dir: /application
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - '.:/application'
    environment:
      - MYSQL_ROOT_PASSWORD=1qazxsw22
      - MYSQL_DATABASE=minos
      - MYSQL_USER=minos
      - MYSQL_PASSWORD=1qazxsw22
    ports:
      - "3308:3306"
  webserver:
    container_name: webserver
    image: nginx:latest
    working_dir: /application
    volumes:
      - '.:/application'
      - './conf-example/docker-setup/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8008:80'
    depends_on:
      - mysql
    links:
      - mysql
  php-fpm:
    build: ./
    working_dir: /application
    volumes:
      - '.:/application'
      - './conf-example/docker-setup/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
  crontab-ui:
    ports:
      - '8009:8000'
    image: alseambusher/crontab-ui
    volumes:
      - '.:/application'
    links:
      - webserver
    depends_on:
      - webserver
  dozzle:
    container_name: dozzle-viewer
    hostname: dozzle
    image: amir20/dozzle
    ports:
      - "8010:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

which I need to add to both files so that running `docker-compose up --build --force-recreate` will install `crontab-ui`

**_the main problem is that:_** 

on this esenario: 
error show by crontab-ui
/bin/sh: php: not found
